### ISSUE TITLE
Create Parse wrapper class to handle all interactions with Parse

### ISSUE THREAD

**Issue by brennanMKE** [GiveNow/givenow-ios#3]
Integrations with Parse are limited. A simple API to wrap the Parse interactions can simplify what is needed for the rest of the app. A blocks-based API will handle all async activity.
- [x] User registration/login
- [ ] Set profile name and photo (optional?)
- [x] Fetch donation centers
- [x] Fetch categories for donation center
- [x] Save new donation
- [x] Fetch donations for a user (provide enum for status)
- [x] Volunteer login/registration
- [x] Request pick up for donation (alert user offering donation, prompting for OK to pick up)
- [x] Set donation as picked up/dropped off
- [ ] Test with automated tests with non-production version of Parse backend

**Comment by brennanMKE** [comment]
@aphexcx I will have questions for you about how you save out Parse objects for the checkboxes listed above. So far the Backend class handles the 2 Cloud Code functions and a few queries which I am just using as a reference for more queries.

**Comment by aphexcx** [comment]
As you've probably already realized, just let the models in https://github.com/GiveNow/givenow-android/tree/master/app/src/main/java/io/givenow/app/models be your guide. The practice I've been using is to create ParseObjects that mirror the columns of each parse table, with convenient getters and setters. (I wish Java had properties... or Scala's case classes. But a girl can dream.)

Since `PickupRequest` is the biggest and most important object, let's take a look at that first. You'll see the query methods, followed by getters/setters, and some convenience methods for generating push notifications. Saving new donations, fetching donations for a user etc are all provided here. For the latter, I don't have an enum though creating one would be nice. Right now it's just a crude raw query and the status is determined if the right columns exist.

**Comment by aphexcx** [comment]
Setting profile name and photo are provided for in `ParseUserHelper`. Check out the nifty usage of Options - not every user has a profile image, or even a name. (Most don't).

**Comment by aphexcx** [comment]
https://parse.com/docs/ios/guide#objects-subclassing-pfobject
Boom, this is how you should create models for Parse objects in swift-land

**Comment by mkulumadzi** [comment]
We'll handle the profile name and photo in a separate issue.
